### ISSUE TITLE
Liquid 4 support

### ISSUE THREAD

**Issue by fastjames** [chamnap/liquid-rails#31]
First off, I want to thank @chamnap for creating and maintaining this gem. It has been incredibly helpful to us in adding Liquid support to our current rails project.

Is there any interest in support for Liquid 4? I saw the comment on https://github.com/Shopify/liquid/pull/441 which indicated that 4.0.0 had a breaking change with how this gem resolves template and partial paths. I spent a day or two on it, and I wound up creating and passing a Liquid::Context into my Resolver class when it's set in ApplicationController. That works for me because the context won't change within a single request in my app.

If anyone else is working on Liquid 4 support, I'd love to hear how you have approached it.

**Comment by streppa-ent** [comment]
I gave it a go a few months ago. I didn't muck about with the Drop stuff so that's unchanged.

You can mix partials (and render) templates. A liquid template can reference a partial and it will look through the template handlers using any registered path resolvers. So you can pull erb templates into liquid templates and vice versa. It will resolve properly. It should anyway. =)

https://github.com/streppa-ent/liquid-rails

**Comment by chamnap** [comment]
Thanks everyone for PRs. I were too busy.

Now, the master branch is fully support with Liquid 4 and Rails 5. For Rails < 5, please use https://rubygems.org/gems/liquid-rails/versions/0.1.4.
